blank_issues_enabled: false
contact_links:
  - name: Question or how-to
    url: https://github.com/friend-to-net-web-developers/micro-utilities/discussions
    about: Not a bug or feature request? Ask here.